config/routes.rb
Rails.application.routes.draw do
  resources :milestones
  root "milestones#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/milestone.rb
class Milestone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  http_basic_authenticate_with name: "matthias", password: "alwayskeeponlearning"

  def index
    @milestones = Milestone.order :created_at
  end

  def new
    @milestone = Milestone.new
  end

  def create
    @milestone = Milestone.create milestone_params

    redirect_to action: :index
  end

  def destroy
    @milestone = Milestone.find params[:id]
    @milestone.destroy

    redirect_to action: :index
  end

  def edit
    @milestone = Milestone.find params[:id]
  end

  def update
    @milestone = Milestone.find params[:id]
    @milestone.assign_attributes milestone_params

    flash[:success] = "You rock, keep on working! :) 🎉" if !@milestone.done_was && @milestone.done
    @milestone.save!
    redirect_to action: :index
  end

  private
  def milestone_params
    params.require(:milestone).permit :title, :done
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatthiasMilestones</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/milestones/_form.html.erb
<%= form_for milestone do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
<% end %>

app/views/milestones/edit.html.erb
<%= render partial: "form", locals: { milestone: @milestone } %>

app/views/milestones/index.html.erb
<h1>Matthias's Learning Milestones</h1>
<% if flash[:success] %>
    <h2 style="color: green; border: 1px solid darkgreen; border-radius: 3px; padding: 5px; background: lightgreen"><%= flash[:success] %></h2>
<% end  %>
<%= link_to "New milestone", new_milestone_path %>
<table>
    <tr>
        <th></th>
        <th>Title</th>
        <th></th>
        <th></th>
    </tr>
    <% @milestones.each do |milestone| %>
        <tr>
            <td><%="✅" if milestone.done?%></td>
            <td><%= milestone.title %></td>
            <td>
                <%= link_to "Delete", milestone_path(milestone), method: :delete %>
                <%= link_to "Edit", edit_milestone_path(milestone) %>
            </td>
            <td>
                <% if milestone.done? %>
                    <%= link_to "undo", milestone_path(milestone, milestone: { done: false }), method: :put %>
                <% else %>
                    <%= link_to "DONE! 😎", milestone_path(milestone, milestone: { done: true }), method: :put %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>

app/views/milestones/new.html.erb
<%= render partial: "form", locals: { milestone: @milestone } %>